# /hybrid_llm_system/config/models.yml
# 各AIエージェントの役割と使用モデル定義

# サブタスクを実行する専門家（ワーカー）エージェント
worker_experts:
  jamba:
    name: "Jamba"
    description: "ユーザーとの対話、創造的な文章生成、タスク計画の立案など、幅広いコミュニケーションタスクを担当する汎用エキスパート。"
    model_path_env: "JAMBA_MODEL_PATH"
    chat_format: "chatml"
    system_prompt: "あなたは、誠実で優秀なAIアシスタントです。与えられた役割に応じて、創造的かつ的確にタスクを実行してください。"

  reporter:
    name: "Reporter" # 名前を役割に合わせて一意に変更
    description: "全エキスパートの成果を統合し、首尾一貫した最終報告書を作成するテクニカルライター。"
    model_path_env: "JAMBA_MODEL_PATH" # Jambaモデルを報告書作成に使用
    chat_format: "chatml"
    system_prompt: "あなたは優秀なテクニカルライターです。提供された全タスクの結果を元に、ユーザーの元の要求に対する包括的で分かりやすい最終報告書を作成してください。"

  liquids4:
    name: "LiquidS4"
    description: "長文の読解、要約、分析、そして長期的な文脈の記憶保持を得意とするエキスパート。"
    model_path_env: "LIQUIDS4_MODEL_PATH"
    chat_format: "llama-2"
    system_prompt: "You are an expert in summarizing and analyzing long texts. Provide a clear, concise, and logical summary."

  hrm:
    name: "HRM"
    description: "複雑な論理パズル、計画立案、ステップバイステップの推論を得意とするエキスパート。"
    model_path_env: "HRM_MODEL_PATH"
    chat_format: "chatml"
    system_prompt: "You are a logical reasoner. Think step by step to solve the problem."

  transformer:
    name: "Transformer"
    description: "コーディング、プログラミング、具体的な関数の実装を得意とするエキスパート。"
    model_path_env: "TRANSFORMER_MODEL_PATH"
    chat_format: "gemma"
    system_prompt: "You are a helpful and intelligent assistant for coding. Provide clean, efficient, and well-commented code."